---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy to dev
    type: deployer
    target:
      region_id: ibm:yp:us-south
      organization: blazej.rutkowski@pl.ibm.com
      space: dev
      application: bluemix-node-mysql-uploader-brutkowski-153
    script: |-
      #!/bin/bash
      ls -l
      echo "${CF_APP}" 
      sed -i "s/@pa_service_instance_name@/\"${CF_APP}\"/g" manifest.yml
      cf push "${CF_APP}"
      # View logs
      #cf logs "${CF_APP}" --recent
